language: android
android:
  components:
    - build-tools-23.0.2
    - android-23

    - extra-android-m2repository

script:
   - ./gradlew cleanTest test && ./gradlew build

notifications:
  email:
    recipients:
      - kristiadi7@gmail.com
      - timotiusnc@gmail.com
    on_success: change
    on_failure: change
